#!/bin/bash

#/*
#*flux-filesystem-expand , a script to resize the disk parton
#* 
#* Copyright (c) 2018 Wind River Systems, Inc.
#* 
#* This program is free software; you can redistribute it and/or modify
#* it under the terms of the GNU General Public License version 2 as
#* published by the Free Software Foundation.
#* 
#* This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#* See the GNU General Public License for more details.
#* 
#* You should have received a copy of the GNU General Public License
#* along with this program; if not, write to the Free Software
#* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#* 
#*/ 

DATA_PARTITION=/dev/disk/by-label/fluxdata

echo -n "Expand ext4 filesystem on $DATA_PARTITION... "
#e2fsck -y $DATA_PARTITION
resize2fs -f $DATA_PARTITION
echo "done."

sync

exit 0
