#!/bin/bash

#/*
#*flux-filesystem-expand , a script to resize the disk parton
#* 
#* Copyright (c) 2018 Wind River Systems, Inc.
#* 
#* This program is free software; you can redistribute it and/or modify
#* it under the terms of the GNU General Public License version 2 as
#* published by the Free Software Foundation.
#* 
#* This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#* See the GNU General Public License for more details.
#* 
#* You should have received a copy of the GNU General Public License
#* along with this program; if not, write to the Free Software
#* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#* 
#*/ 

DATA_PARTITION=/dev/disk/by-label/fluxdata
FREESPACE_LIMIT=10
datapart=$(readlink -f ${DATA_PARTITION})
datadev=$(lsblk $datapart -n -o PKNAME)
datadevnum=$(echo ${datapart} | sed 's/\(.*\)\(.\)$/\2/')

log_info() { echo "$0[$$]: $*" >&2; }
log_error() { echo "$0[$$]: ERROR $*" >&2; }

fluxdataexpander_enabled() {
    for freespace in $(parted -m /dev/$datadev unit MiB print free | grep free | cut -d: -f4 | sed 's/MiB//g'); do
        if [ $(echo $freespace \> $FREESPACE_LIMIT | bc -l) == "1" ]; then
            return 0
        fi
    done
    return 1
}

fluxdataexpander_run() {
    log_info "fluxdataexpander: Expand data partition... "
    parted -s /dev/$datadev -- resizepart $datadevnum -1s
    log_info "fluxdataexpander: Finished expanding data partition."

    partprobe
    sync
}

if [ fluxdataexpander_enabled ]; then
        fluxdataexpander_run
fi

echo -n "Expand ext4 filesystem on $DATA_PARTITION... "
#e2fsck -y $DATA_PARTITION
resize2fs -f $DATA_PARTITION
echo "done."

sync

exit 0
