#!/bin/bash

#
# Copyright (C) 2018 Wind River Systems Inc.
#

DATA_PARTITION=/dev/disk/by-label/fluxdata

echo -n "Expand ext4 filesystem on $DATA_PARTITION... "
#e2fsck -y $DATA_PARTITION
resize2fs -f $DATA_PARTITION
echo "done."

sync

exit 0
